services:
  math_dev:
    build: .
    container_name: math_dev
    hostname: math_dev
    user: "node"
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev"]
